Added type annotations.
adafruit/Adafruit_CircuitPython_EPD pull request #64
Opened 2023-05-02 21:49 UTC by sdomoszlai13

I'm not sure however if the type annotations are exact enough. Please let me know how they're supposed to be done if the current way is wrong.

2023-05-08 16:28 UTC, FoamyGuy requested changes
@sdomoszlai13 Thanks for working on this!

Are you interested in adding type annotations for any of the other files in this library as well?

I have afew suggested changes noted below.

2023-05-08 16:28 UTC, FoamyGuy commented on adafruit_epd/mcp_sram.py
> +    def write16(self, addr: int, value: Any, reg: int = SRAM_WRITE):
Same as the other, I think the code is expecting `value` to be `int` in this case

2023-05-09 13:21 UTC, sdomoszlai13 commented
Thanks for the suggestions, I'll implement them!
And yes, I'm planning to add type annotations in other files in this library as well.

2023-05-09 13:22 UTC, sdomoszlai13 commented
Thanks for the suggestions, I'll implement them!
And yes, I'm planning to add type annotations in other files in this library as well.

2023-05-09 22:01 UTC, closed without merging